### ISSUE TITLE
Ready for Review

### ISSUE THREAD

**Issue by ranimurali412** [ranimurali412/code4policy-team-a1#113]
Our final project is ready for review!

**Task Boards:** 
- [x] Sprint 1: https://github.com/ranimurali412/code4policy-team-a1/projects/2 
- [x] Sprint 2: https://github.com/ranimurali412/code4policy-team-a1/projects/4

**Other Artifacts:**
- [x] Backlog: https://github.com/ranimurali412/code4policy-team-a1/projects/1
- [x] Burndown chart: https://github.com/ranimurali412/code4policy-team-a1/blob/main/data/burndown_chart/burndown_chart.txt
- [x] Retrospective Google form
- [x] Final Project rendered on GitHub pages: https://ranimurali412.github.io/code4policy-team-a1/ 
- [x] Data folder: https://github.com/ranimurali412/code4policy-team-a1/tree/main/data
- [x] Final project technical reflection from each student 
- [x] Final project reflection from each student
